name: bexit
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cache
  shared_preferences: ^2.0.15

  # Stack
  stacked: ^3.0.1
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.9

  # UI
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  circular_profile_avatar: ^2.0.5
  images_picker: ^1.2.11
  overlay_support: ^2.1.0
  loading_animation_widget: ^1.2.0+4

  # Injectables
  injectable: ^2.1.0

  # Utils
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2

  # Networking
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  stacked_generator: ^0.8.0+1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/circular-std-medium-500.ttf
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Medium.ttf
  uses-material-design: true

  assets:
    - .env
    - .env.staging

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true